### ISSUE TITLE
Adding additional BatV and Temperature measurements 

### ISSUE THREAD

**Issue by sua-dev** [kmartinez/icetracker-py#3]
We need to introduce two extra measurements that are convenient to have.
Readings are measured from rovers and sent back to the base for processing. 
We want to make sure we can record `battery voltage` and `temperature`, which can easily be done using Qwiic connectors. Whether these are to be recorded on the base stations or rovers is to be decided, but the matter to consider is updating the ingestor from the server side to be able to accept these new measurements.
It would also be useful to get in touch with the GDP team to have them spend a bit of time ensuring that all the files aren't stored within a container.

**Comment by kmartinez** [comment]
BatV needed on all nodes
temperature - probably all too so data is similar

**Comment by sua-dev** [comment]
Just added some extra lines, and pin definitions for the UARTs, mainly checking if the radio and GPS operate optimally just from the Thing+. I don't have a DS3231 module with me, but can confidently say that the remaining boards will just work fine without a PSU board.
